#!/bin/bash

chars=(" [/]" " [|]" " [\\]" " [-]")

printed=0

printf "\x1b[33mLoading..\n\x1b[0m"
for (( i=0; i<100; i++))
do
	sleep 0.1
	let mod=$i%4
	if [ $mod -eq 0 ]
	then
		(( printed++ ))
	fi
	printf "["
	for (( k=0; k<$printed; k++ ))
	do
		printf "/"
	done
	for (( j=25; j>$printed; j--))
	do
		printf "."
	done
	printf "]"
	printf "\r"
done
printf "\x1b[32mReady!                        \n\x1b[0m"
